# CI workflow
name: CI

on:
  push:
    branches:
      - '*' # matches every branch
  pull_request:
    branches:
      - master

jobs:
  # job 1:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      # step 1: checkout repository code
      - name: Checkout code into workspace directory
        uses: actions/checkout@v2

      # step 2: set up Node.js
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      # step 3: install dependencies
      - name: Install dependencies
        run: npm ci

      # step 4: run format check
      - name: Check code format
        run: npm run lint

  # job 2: test library code
  test:
    name: Test
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 13.x, 14.x]
    steps:
      # step 1: checkout repository code
      - name: Checkout code into workspace directory
        uses: actions/checkout@v2

      # step 2: set up Node.js
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      # step 3: install dependencies
      - name: Install dependencies
        run: npm ci

      # step 4: run unit tests
      - name: Run unit tests
        run: npm test
